### ISSUE TITLE
Python env

### ISSUE THREAD

**Issue by sebkaz** [mateuszkasprowicz/fairness-toolkits#1]
It will be good to have information about Python env.

Python env from requirements can't be made for:
Python 3.9  and  Python 3.11 
- (ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement pywin32==305.1 (from versions: none)
ERROR: No matching distribution found for pywin32==305.1)

**Comment by mateuszkasprowicz** [comment]
Thanks for pointing this out. What is the best practice to store this info? I use conda for env management.

**Comment by sebkaz** [comment]
You can add python version in README.md file.  
Or You can add env preparing code 
```bash
python3.X -m venv venv
source venv/bin/activate
(venv) pip install --upgrade pip setuptools wheel
(venv) pip install -r requirements.txt
```
